# SPIRE Agent configuration
#
# Not used in Lab 1.
#
# Added in Lab 2.

agent {
    trust_domain = "lab.local"

    data_dir = "/run/spire/data"
    log_level = "DEBUG"

    server_address = "spire-server"
    server_port = "8081"

    socket_path = "/run/spire/sockets/agent.sock"

    insecure_bootstrap = true
}

plugins {
    NodeAttestor "join_token" {
        plugin_data {}
    }

    KeyManager "disk" {
        plugin_data {
            directory = "/run/spire/data"
        }
    }

    # LAB 2: required so the agent can start.
    # LAB 3: we will actually use Docker selectors from this plugin.
    WorkloadAttestor "docker" {
        plugin_data {
            docker_socket_path = "unix:///var/run/docker.sock"
        }
    }

}