# SPIRE Server configuration
#
# Not used in Lab 1.
#
# Added in Lab 2.

server {
    trust_domain = "lab.local"

    bind_address = "0.0.0.0"
    bind_port = "8081"

    data_dir = "/run/spire/data"
    log_level = "DEBUG"

    # Use SPIRE default admin socket
    socket_path = "/tmp/spire-server/private/api.sock"
}

plugins {
    DataStore "sql" {
        plugin_data {
            database_type = "sqlite3"
            connection_string = "/run/spire/data/datastore.sqlite3"
        }
    }

    NodeAttestor "join_token" {
        plugin_data {}
    }

    KeyManager "disk" {
        plugin_data {
            keys_path = "/run/spire/data/keys.json"
        }
    }
}